// SPDX-FileCopyrightText: 2026 Goobstation
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.MobSwitcher;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;

namespace Content.Goobstation.Client.MobSwitcher;

[GenerateTypedNameReferences]
public sealed partial class MobSwitcherWindow : FancyWindow
{
    private static readonly Robust.Client.Graphics.StyleBoxFlat SelectedStyle = new()
    {
        BackgroundColor = new Robust.Shared.Maths.Color(0.2f, 0.4f, 0.8f, 0.35f),
    };

    private readonly IEntityManager _entMan;
    private NetEntity? _selected;
    private List<MobSwitcherEntry> _entries = new();

    public event Action? AddCurrentPressed;
    public event Action<NetEntity>? SwitchPressed;
    public event Action<NetEntity>? RemovePressed;
    public event Action? ResetPressed;

    public MobSwitcherWindow()
    {
        RobustXamlLoader.Load(this);
        _entMan = IoCManager.Resolve<IEntityManager>();

        AddCurrentButton.OnPressed += _ => AddCurrentPressed?.Invoke();

        SwitchButton.OnPressed += _ =>
        {
            if (_selected is { } sel)
                SwitchPressed?.Invoke(sel);
        };

        RemoveButton.OnPressed += _ =>
        {
            if (_selected is { } sel)
                RemovePressed?.Invoke(sel);
        };

        ResetButton.OnPressed += _ => ResetPressed?.Invoke();

        UpdateButtonStates();
    }

    /// <summary>
    /// Rebuilds the entry list from freshly-pushed server state.
    /// </summary>
    public void Populate(List<MobSwitcherEntry> entries)
    {
        _entries = entries;

        // Keep selection valid
        if (_selected is { } sel)
        {
            var found = false;
            for (var i = 0; i < entries.Count; i++)
            {
                if (entries[i].Entity == sel) { found = true; break; }
            }
            if (!found) _selected = null;
        }

        EntryContainer.DisposeAllChildren();

        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];
            EntryContainer.AddChild(BuildRow(entry, entry.Entity == _selected));
        }

        UpdateButtonStates();
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private PanelContainer BuildRow(MobSwitcherEntry entry, bool selected)
    {
        var panel = new PanelContainer
        {
            MinSize = new Vector2(0, 48),
            HorizontalExpand = true,
            MouseFilter = Control.MouseFilterMode.Stop,
        };

        if (selected)
            panel.PanelOverride = SelectedStyle;

        var hbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 4),
            SeparationOverride = 6,
            MouseFilter = Control.MouseFilterMode.Ignore,
        };

        hbox.AddChild(new SpriteView(entry.Entity, _entMan)
        {
            MinSize = new Vector2(32, 32),
            SetSize = new Vector2(32, 32),
            OverrideDirection = Direction.South,
            MouseFilter = Control.MouseFilterMode.Ignore,
        });

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalAlignment = Control.VAlignment.Center,
            HorizontalExpand = true,
            MouseFilter = Control.MouseFilterMode.Ignore,
        };

        vbox.AddChild(new Label
        {
            Text = entry.CharacterName,
            HorizontalExpand = true,
            ClipText = true,
            MouseFilter = Control.MouseFilterMode.Ignore,
        });

        vbox.AddChild(new Label
        {
            Text = entry.MobId,
            HorizontalExpand = true,
            ClipText = true,
            Modulate = new Robust.Shared.Maths.Color(0.7f, 0.7f, 0.7f, 1f),
            MouseFilter = Control.MouseFilterMode.Ignore,
        });

        hbox.AddChild(vbox);
        panel.AddChild(hbox);

        // Only select on left mouse click
        var captured = entry.Entity;
        panel.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _selected = captured;
            RefreshHighlights();
            UpdateButtonStates();
        };

        return panel;
    }

    private void RefreshHighlights()
    {
        for (var i = 0; i < EntryContainer.ChildCount && i < _entries.Count; i++)
        {
            if (EntryContainer.GetChild(i) is PanelContainer panel)
                panel.PanelOverride = _entries[i].Entity == _selected ? SelectedStyle : null;
        }
    }

    private void UpdateButtonStates()
    {
        SwitchButton.Disabled = _selected == null;
        RemoveButton.Disabled = _selected == null;
    }
}
